#Dataset Description

\

## The dataset contains information about road traffic accidents with the following columns:

`Time`: Time of the accident

`Day_of_week`: Day of the week when the accident occurred

`Age_band_of_driver`: Age group of the driver

`Sex_of_driver`: Gender of the driver

`Educational_level`: Educational level of the driver

`Vehicle_driver_relation`: Relationship of the driver to the vehicle

`Driving_experience`: Driving experience of the driver

`Type_of_vehicle`: Type of vehicle involved in the accident

`Owner_of_vehicle`: Owner of the vehicle

`Service_year_of_vehicle`: Service years of the vehicle

`Area_accident_occured`: Area where the accident occurred

`Lanes_or_Medians`: Lanes or medians at the accident site

`Road_allignment`: Road alignment at the accident site

`Types_of_Junction`: Type of junction at the accident site

`Road_surface_type`: Type of road surface at the accident site

`Road_surface_conditions`: Road surface conditions at the accident site

`Light_conditions`: Light conditions at the time of the accident

`Weather_conditions`: Weather conditions at the time of the accident

`Type_of_collision`: Type of collision

`Number_of_vehicles_involved`: Number of vehicles involved in the accident

`Number_of_casualties`: Number of casualties in the accident

`Vehicle_movement`: Movement of the vehicle during the accident

`Casualty_class`: Class of casualty (driver, passenger, pedestrian)

`Sex_of_casualty`: Gender of the casualty

`Age_band_of_casualty`: Age group of the casualty

`Casualty_severity`: Severity of the casualty

`Work_of_casuality`: Occupation of the casualty

`Fitness_of_casuality`: Fitness of the casualty

`Pedestrian_movement`: Movement of the pedestrian

`Cause_of_accident`: Cause of the accident

`Accident_severity`: Severity of the accident

# Tasks

##1. Data Cleaning

### Read the dataset

In [194]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\s3odk\Downloads\Task (1) Dataset.csv")

In [168]:
df

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12311,16:15:00,Wednesday,31-50,Male,NaN,Employee,2-5yr,Lorry (11?40Q),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12312,18:00:00,Sunday,Unknown,Male,Elementary school,Employee,5-10yr,Automobile,Owner,NaN,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12313,13:55:00,Sunday,Over 51,Male,Junior high school,Employee,5-10yr,Bajaj,Owner,2-5yrs,...,Other,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
12314,13:55:00,Sunday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,2-5yrs,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,Driving under the influence of drugs,Slight Injury
12315,13:55:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Other,Owner,2-5yrs,...,Stopping,Pedestrian,Female,5,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the right,Slight Injury

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            11575 non-null  object
 5   Vehicle_driver_relation      11737 non-null  object
 6   Driving_experience           11487 non-null  object
 7   Type_of_vehicle              11366 non-null  object
 8   Owner_of_vehicle             11834 non-null  object
 9   Service_year_of_vehicle      8388 non-null   object
 10  Defect_of_vehicle            7889 non-null   object
 11  Area_accident_occured        12077 non-null  object
 12  Lanes_or_Medians             11931 non-null  object
 13  Road_allignment              12174 non-null  object
 14  Types_of_Junction            11429 non-null  object
 15  Road_surface_type            12144 non-null  object
 16  Road_surface_conditions      12316 non-null  object
 17  Light_conditions             12316 non-null  object
 18  Weather_conditions           12316 non-null  object
 19  Type_of_collision            12161 non-null  object
 20  Number_of_vehicles_involved  12316 non-null  int64
 21  Number_of_casualties         12316 non-null  int64
 22  Vehicle_movement             12008 non-null  object
 23  Casualty_class               12316 non-null  object
 24  Sex_of_casualty              12316 non-null  object
 25  Age_band_of_casualty         12316 non-null  object
 26  Casualty_severity            12316 non-null  object
 27  Work_of_casuality            9118 non-null   object
 28  Fitness_of_casuality         9681 non-null   object
 29  Pedestrian_movement          12316 non-null  object
 30  Cause_of_accident            12316 non-null  object
 31  Accident_severity            12316 non-null  object
dtypes: int64(2), object(30)
memory usage: 3.0+ MB

In [133]:
df.sample(10)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
88,7:40:00,Monday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,2-5yrs,...,Going straight,None,None,None,None,Driver,Normal,Not a Pedestrian,No distancing,Serious Injury
1546,17:48:00,Tuesday,31-50,Male,Junior high school,Employee,2-5yr,Taxi,Owner,2-5yrs,...,Going straight,Driver or rider,Male,18-30,3,NaN,Normal,Not a Pedestrian,Driving carelessly,Slight Injury
3375,16:25:00,Monday,31-50,Male,Junior high school,Employee,5-10yr,Automobile,Governmental,None,...,Other,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Driving at high speed,Slight Injury
904,19:00:00,Wednesday,Under 18,Male,Junior high school,Employee,5-10yr,Lorry (41?100Q),Owner,Above 10yr,...,Going straight,Passenger,Female,Under 18,3,NaN,NaN,Not a Pedestrian,No priority to pedestrian,Slight Injury
5616,16:00:00,Tuesday,None,Male,Junior high school,Employee,5-10yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,18-30,3,Self-employed,Normal,Not a Pedestrian,Driving carelessly,Slight Injury
704,17:45:00,Tuesday,None,Female,Junior high school,Employee,Below 1yr,Lorry (41?100Q),Owner,None,...,Going straight,None,None,None,None,Other,Normal,Not a Pedestrian,No distancing,Slight Injury
7497,18:29:00,Thursday,18-30,Male,Elementary school,Owner,5-10yr,Automobile,Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Driving carelessly,Slight Injury
11557,20:40:00,Friday,18-30,Male,Junior high school,Employee,2-5yr,Public (12 seats),Owner,2-5yrs,...,Going straight,None,None,None,None,Driver,Normal,Not a Pedestrian,Turnover,Slight Injury
7000,14:35:00,Wednesday,18-30,Male,Writing & reading,Employee,Below 1yr,NaN,Owner,None,...,Going straight,Passenger,Male,Over 51,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
248,15:55:00,Thursday,18-30,Male,Junior high school,Employee,2-5yr,Public (13?45 seats),Owner,NaN,...,Going straight,Driver or rider,Male,Over 51,3,NaN,NaN,Not a Pedestrian,Changing lane to the right,Slight Injury

In [19]:
df.duplicated().sum()

0

### Handle Missing Values

In [11]:
df.isnull().value_counts().sum()

12316

In [125]:
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level               741
Vehicle_driver_relation         579
Driving_experience              829
Type_of_vehicle                 950
Owner_of_vehicle                482
Service_year_of_vehicle        3928
Defect_of_vehicle              4427
Area_accident_occured           239
Lanes_or_Medians                385
Road_allignment                 142
Types_of_Junction               887
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions                0
Type_of_collision               155
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                308
Casualty_class                 4443
Sex_of_casualty                   0
Age_band_of_casualty              0
Casualty_severity                 0
Work_of_casuality              3198
Fitness_of_casuality           2635
Pedestrian_movement               0
Cause_of_accident                 0
Accident_severity                 0
dtype: int64

In [195]:

df['Casualty_class'] = df['Casualty_class'].replace('na', None)





# df['Casualty_class'] = df['Casualty_class'](dtype='str')
# df['Casualty_class'].info()

In [196]:
df = df.replace('Unknown', None)
df

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,None,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,None,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,None,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12311,16:15:00,Wednesday,31-50,Male,NaN,Employee,2-5yr,Lorry (11?40Q),Owner,NaN,...,Going straight,None,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12312,18:00:00,Sunday,None,Male,Elementary school,Employee,5-10yr,Automobile,Owner,NaN,...,Other,None,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12313,13:55:00,Sunday,Over 51,Male,Junior high school,Employee,5-10yr,Bajaj,Owner,2-5yrs,...,Other,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
12314,13:55:00,Sunday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,2-5yrs,...,Other,None,na,na,na,Driver,Normal,Not a Pedestrian,Driving under the influence of drugs,Slight Injury
12315,13:55:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Other,Owner,2-5yrs,...,Stopping,Pedestrian,Female,5,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the right,Slight Injury

In [129]:
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level               741
Vehicle_driver_relation         579
Driving_experience              829
Type_of_vehicle                 950
Owner_of_vehicle                482
Service_year_of_vehicle        3928
Defect_of_vehicle              4427
Area_accident_occured           239
Lanes_or_Medians                385
Road_allignment                 142
Types_of_Junction               887
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions                0
Type_of_collision               155
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                308
Casualty_class                 4443
Sex_of_casualty                4443
Age_band_of_casualty           4443
Casualty_severity              4443
Work_of_casuality              3198
Fitness_of_casuality           2635
Pedestrian_movement               0
Cause_of_accident                 0
Accident_severity                 0
dtype: int64

In [197]:
df = df.replace('Unknown', None)

In [198]:
df = df.replace('na', None)

In [163]:
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver             1548
Sex_of_driver                   178
Educational_level               841
Vehicle_driver_relation         593
Driving_experience              829
Type_of_vehicle                 950
Owner_of_vehicle                482
Service_year_of_vehicle        6811
Defect_of_vehicle              4427
Area_accident_occured           261
Lanes_or_Medians                442
Road_allignment                 142
Types_of_Junction              1078
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions              292
Type_of_collision               169
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                396
Casualty_class                 4443
Sex_of_casualty                4443
Age_band_of_casualty           4443
Casualty_severity              4443
Work_of_casuality              3217
Fitness_of_casuality           2635
Pedestrian_movement               0
Cause_of_accident                25
Accident_severity                 0
dtype: int64

In [122]:
# df['Casualty_class'] = df['Casualty_class'].str.replace('na', None)

TypeError: repl must be a string or callable

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            11575 non-null  object
 5   Vehicle_driver_relation      11737 non-null  object
 6   Driving_experience           11487 non-null  object
 7   Type_of_vehicle              11366 non-null  object
 8   Owner_of_vehicle             11834 non-null  object
 9   Service_year_of_vehicle      8388 non-null   object
 10  Defect_of_vehicle            7889 non-null   object
 11  Area_accident_occured        12077 non-null  object
 12  Lanes_or_Medians             11931 non-null  object
 13  Road_allignment              12174 non-null  object
 14  Types_of_Junction            11429 non-null  object
 15  Road_surface_type            12144 non-null  object
 16  Road_surface_conditions      12316 non-null  object
 17  Light_conditions             12316 non-null  object
 18  Weather_conditions           12316 non-null  object
 19  Type_of_collision            12161 non-null  object
 20  Number_of_vehicles_involved  12316 non-null  int64
 21  Number_of_casualties         12316 non-null  int64
 22  Vehicle_movement             12008 non-null  object
 23  Casualty_class               12316 non-null  object
 24  Sex_of_casualty              12316 non-null  object
 25  Age_band_of_casualty         12316 non-null  object
 26  Casualty_severity            12316 non-null  object
 27  Work_of_casuality            9118 non-null   object
 28  Fitness_of_casuality         9681 non-null   object
 29  Pedestrian_movement          12316 non-null  object
 30  Cause_of_accident            12316 non-null  object
 31  Accident_severity            12316 non-null  object
dtypes: int64(2), object(30)
memory usage: 3.0+ MB

In [243]:
df.sample(5)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
8872,23:54:00,Saturday,18-30,Male,Junior high school,Employee,1-2,Stationwagen,Owner,2-5yrs,...,Going straight,Pedestrian,Female,Under 18,3,NaN,NaN,Not a Pedestrian,No priority to vehicle,Serious Injury
10076,17:22:00,Tuesday,Over 51,Male,Junior high school,Employee,10,NaN,Other,None,...,Going straight,None,None,None,None,Driver,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
1180,9:00:00,Friday,Over 51,Male,Junior high school,Employee,5-10,Automobile,Owner,Below 1yr,...,Going straight,None,None,None,None,Driver,Normal,Not a Pedestrian,None,Slight Injury
2785,15:10:00,Sunday,18-30,Male,NaN,NaN,<NA>,Lorry (41?100Q),Owner,NaN,...,Going straight,Pedestrian,Male,Under 18,3,Driver,Normal,Unknown or other,Getting off the vehicle improperly,Slight Injury
5613,9:17:00,Tuesday,None,Male,Junior high school,Employee,2-5,Pick up upto 10Q,Owner,2-5yrs,...,Going straight,Pedestrian,Female,31-50,3,Self-employed,Normal,Not a Pedestrian,Overturning,Slight Injury

In [230]:
# df['Age_band_of_casualty'] = df['Age_band_of_casualty'].replace('Over ', "")
df['Age_band_of_casualty'] = df['Age_band_of_casualty'].astype("string") 
df['Age_band_of_casualty'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 12316 entries, 0 to 12315
Series name: Age_band_of_casualty
Non-Null Count  Dtype
--------------  -----
12316 non-null  string
dtypes: string(1)
memory usage: 96.3 KB

In [231]:
df['Driving_experience'] = df['Driving_experience'].astype("string")

In [226]:
df['Age_band_of_casualty'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 12316 entries, 0 to 12315
Series name: Age_band_of_casualty
Non-Null Count  Dtype
--------------  -----
12316 non-null  object
dtypes: object(1)
memory usage: 96.3+ KB

In [244]:
# df['Driving_experience'] = df['Driving_experience'].replace('Under', "" )
df['Driving_experience'] = df['Driving_experience'].str.replace(" Over"," ").str.replace("yr",'').str.replace("Above " ,'')
# df.sample(5)
df['Driving_experience']

0         1-2
1          10
2         1-2
3        5-10
4         2-5
         ...
12311     2-5
12312    5-10
12313    5-10
12314      10
12315    5-10
Name: Driving_experience, Length: 12316, dtype: string

In [250]:
#  df["Age_band_of_driver"] =df["Age_band_of_driver"].str.replace("Over "," ") 
# df['Driving_experience'].str.replace(" Over"," ")
df["Age_band_of_driver"]

0        18-30
1        31-50
2        18-30
3        18-30
4        18-30
         ...
12311    31-50
12312     None
12313       51
12314    18-30
12315    18-30
Name: Age_band_of_driver, Length: 12316, dtype: object

In [251]:
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver             1548
Sex_of_driver                   178
Educational_level               841
Vehicle_driver_relation         593
Driving_experience              829
Type_of_vehicle                 950
Owner_of_vehicle                482
Service_year_of_vehicle        6811
Defect_of_vehicle              4427
Area_accident_occured           261
Lanes_or_Medians                442
Road_allignment                 142
Types_of_Junction              1078
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions              292
Type_of_collision               169
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                396
Casualty_class                 4443
Sex_of_casualty                4443
Age_band_of_casualty              0
Casualty_severity              4443
Work_of_casuality              3217
Fitness_of_casuality           2635
Pedestrian_movement               0
Cause_of_accident                25
Accident_severity                 0
dtype: int64

In [253]:
# df["Casualty_class"]
df.sample(5)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
2966,19:55:00,Sunday,31-50,Male,Junior high school,Employee,10,Public (13?45 seats),Owner,2-5yrs,...,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Getting off the vehicle improperly,Slight Injury
2663,7:25:00,Tuesday,51,Male,Junior high school,Employee,10,Automobile,Owner,2-5yrs,...,Going straight,Driver or rider,Female,18-30,3,Self-employed,Normal,Not a Pedestrian,No distancing,Serious Injury
2190,21:51:00,Wednesday,18-30,Male,Junior high school,Employee,10,Automobile,Governmental,NaN,...,Going straight,None,None,None,None,Driver,Normal,Not a Pedestrian,Changing lane to the left,Slight Injury
1609,12:44:00,Wednesday,31-50,Male,Above high school,Employee,10,Automobile,Owner,5-10yrs,...,Moving Backward,Passenger,Female,Under 18,3,Driver,Normal,Not a Pedestrian,Driving carelessly,Serious Injury
421,9:05:00,Friday,31-50,Male,Elementary school,Employee,Below 1,Automobile,Owner,NaN,...,Going straight,None,None,None,None,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury

####  Missing Values

# Cause_of_accident , 
# df['Cause_of_accident'] =df['Cause_of_accident'].dropna()  
# df.drop(columns= 'Cause_of_accident' , inplace = True)
df = df.dropna(subset = 'Cause_of_accident' , inplace= True)
df.isnull().sum()

In [256]:
df.drop(columns= 'Cause_of_accident' , inplace = True)

In [254]:
# df['Cause_of_accident'] = df.dropna(subset = 'Cause_of_accident' , inplace= True)
# df.isnull().sum()

In [174]:
df

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,None,None,None,None,NaN,NaN,Not a Pedestrian,None,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,None,None,None,None,NaN,NaN,Not a Pedestrian,None,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,None,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,None,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,None,None,None,None,NaN,NaN,Not a Pedestrian,None,Slight Injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12311,16:15:00,Wednesday,31-50,Male,NaN,Employee,2-5yr,Lorry (11?40Q),Owner,NaN,...,Going straight,None,None,None,None,Driver,Normal,Not a Pedestrian,None,Slight Injury
12312,18:00:00,Sunday,None,Male,Elementary school,Employee,5-10yr,Automobile,Owner,NaN,...,Other,None,None,None,None,Driver,Normal,Not a Pedestrian,None,Slight Injury
12313,13:55:00,Sunday,Over 51,Male,Junior high school,Employee,5-10yr,Bajaj,Owner,2-5yrs,...,Other,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,None,Serious Injury
12314,13:55:00,Sunday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,2-5yrs,...,Other,None,None,None,None,Driver,Normal,Not a Pedestrian,None,Slight Injury
12315,13:55:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Other,Owner,2-5yrs,...,Stopping,Pedestrian,Female,5,3,Driver,Normal,Crossing from nearside - masked by parked or s...,None,Slight Injury

In [265]:
# df['Age_band_of_driver'].fillna(df['Age_band_of_driver'].mode()[0])
# df['Age_band_of_driver'] = df['Age_band_of_driver'].astype("float") 
# df['Age_band_of_driver'] =df['Age_band_of_driver'].fillna(df['Age_band_of_driver'].mode()[0])
df["Sex_of_driver"] =df["Sex_of_driver"].fillna(df["Sex_of_driver"].mode()[0])
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level               839
Vehicle_driver_relation         593
Driving_experience              829
Type_of_vehicle                 946
Owner_of_vehicle                481
Service_year_of_vehicle        6800
Defect_of_vehicle              4418
Area_accident_occured           260
Lanes_or_Medians                441
Road_allignment                 142
Types_of_Junction              1077
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions              291
Type_of_collision               168
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                392
Casualty_class                 4432
Sex_of_casualty                4432
Age_band_of_casualty              0
Casualty_severity              4432
Work_of_casuality              3211
Fitness_of_casuality           2628
Pedestrian_movement               0
Accident_severity                 0
dtype: int64

In [270]:
# # df["Educational_level"] =df["Educational_level"].fillna(df["Educational_level"].mode()[0])
# df["Vehicle_driver_relation"] =df["Vehicle_driver_relation"].fillna(df["Vehicle_driver_relation"].mode()[0])
# disnullull().sum()

In [260]:
# df['Age_band_of_driver'].info()
# df['Age_band_of_driver'].fillna(df['Age_band_of_driver'].mean())

<class 'pandas.core.series.Series'>
Int64Index: 12291 entries, 0 to 12315
Series name: Age_band_of_driver
Non-Null Count  Dtype
--------------  -----
10745 non-null  object
dtypes: object(1)
memory usage: 192.0+ KB

In [269]:
df.drop(columns= 'Service_year_of_vehicle' , inplace = True)

In [275]:
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level                 0
Vehicle_driver_relation           0
Driving_experience                0
Type_of_vehicle                 946
Owner_of_vehicle                481
Defect_of_vehicle              4418
Area_accident_occured           260
Lanes_or_Medians                441
Road_allignment                 142
Types_of_Junction              1077
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions              291
Type_of_collision               168
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                392
Casualty_class                 4432
Sex_of_casualty                4432
Age_band_of_casualty              0
Casualty_severity              4432
Work_of_casuality              3211
Fitness_of_casuality           2628
Pedestrian_movement               0
Accident_severity                 0
dtype: int64

In [274]:
# df["Driving_experience"].info()
df["Driving_experience"] =df["Driving_experience"].fillna(df["Driving_experience"].mode()[0])

### Correct any inconsistent data entries.

In [282]:
df.sample(5)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Defect_of_vehicle,...,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Accident_severity
2367,16:00:00,Sunday,18-30,Male,Elementary school,Employee,10,Lorry (11?40Q),Organization,No defect,...,1,Entering a junction,None,None,None,None,Driver,Normal,Not a Pedestrian,Slight Injury
7590,19:30:00,Thursday,18-30,Male,Junior high school,Employee,1-2,Taxi,Owner,NaN,...,3,Stopping,Driver or rider,Male,18-30,3,NaN,NaN,Not a Pedestrian,Slight Injury
9279,21:55:00,Wednesday,Under 18,Male,Elementary school,Owner,10,NaN,Owner,No defect,...,1,Going straight,Passenger,Female,Under 18,3,NaN,NaN,Not a Pedestrian,Slight Injury
6245,22:17:00,Saturday,18-30,Male,Junior high school,Owner,2-5,Automobile,Governmental,No defect,...,6,Going straight,None,None,None,None,NaN,NaN,Not a Pedestrian,Slight Injury
7211,18:05:00,Thursday,31-50,Male,Junior high school,Employee,10,Automobile,Owner,No defect,...,1,Moving Backward,Driver or rider,Male,18-30,3,NaN,NaN,Not a Pedestrian,Serious Injury

In [309]:
# df['Day_of_week'] = df['Day_of_week'].astype("category")

AttributeError: 'Series' object has no attribute 'as_ordered'

### Ensure data types are appropriate for each column.

---

In [283]:
df['Sex_of_driver'] = df['Sex_of_driver'].astype("category")

In [284]:
df['Educational_level'] = df['Educational_level'].astype("category")

In [285]:
# Vehicle_driver_relation
df['Vehicle_driver_relation'] = df['Vehicle_driver_relation'].astype("category")

In [286]:
df['Owner_of_vehicle'] = df['Owner_of_vehicle'].astype("category")

In [287]:

df['Vehicle_movement'] = df['Vehicle_movement'].astype("category")

In [289]:


df['Sex_of_casualty'] = df['Sex_of_casualty'].astype("category")

In [327]:
df['Age_band_of_driver'] = df['Age_band_of_driver'].str.replace("Under "," ")

df[['lower_age','upper_age']] = df['Age_band_of_driver'].str.split('-', expand = True) 
df['lower_age'] = df['lower_age'].astype(int) 
df['upper_age'] =df['upper_age'].astype(int)

In [329]:
df['upper_age'] 
df['lower_age']

after this step we can calculate the relationship between age and sex of drive

## 2. Exploratory Data Analysis (EDA)

### Perform summary statistics on the dataset.

In [276]:
df.describe()

       Number_of_vehicles_involved  Number_of_casualties
count                 12291.000000          12291.000000
mean                      2.040599              1.548287
std                       0.688907              1.007381
min                       1.000000              1.000000
25%                       2.000000              1.000000
50%                       2.000000              1.000000
75%                       2.000000              2.000000
max                       7.000000              8.000000

### Identify and analyze patterns in the data.

### Visualize the distribution of key variables (e.g., Age_band_of_driver, Type_of_vehicle).

In [314]:
# sns.scatterplot(x = "Day_of_week" , y="Sex_of_driver", data = df)

# sns.barplot(x = "Day_of_week" , y="Time" , data = df);
# sns.regplot(x = "Day_of_week" , y = 'Number_of_vehicles_involved' ,data = df)
import matplotlib.pyplot as plt
df.Number_of_vehicles_involved.plot(kind = 'bar')

### Explore relationships between variables (e.g., Age_band_of_driver vs. Accident_severity).

In [291]:
# import seaborn as sns 
# sns.heatmap(df.corr())

## 3. Data Visualization

* Ensure the visualizations are clear and informative.

### Create visualizations to illustrate the findings from the EDA.

### Use appropriate plots such as histograms, bar charts, pie charts, scatter plots, and heatmaps.

## 4. Insights and Conclusions

* <h3>Summarize the key insights gained from the data analysis.<h3/>
* <h3>Draw conclusions based on the patterns observed in the data.<h3/>

must study more ..
thank you